load("@rules_cuda//cuda:defs.bzl", "cuda_binary", "cuda_test")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "test1",
    srcs = ["test1.cc"],
)

cuda_binary(
    name = "test2",
    srcs = ["test2.cu"],
)

cc_binary(
    name = "test3",
    srcs = ["test3.cc"],
)

cuda_binary(
    name = "test4",
    srcs = ["test4.cu"],
)

cc_binary(
    name = "test5",
    srcs = ["test5.cc"],
)

cuda_binary(
    name = "test6",
    srcs = ["test6.cu"],
)